sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
install:
  - npm install -g babel-cli
script:
  - npm run cover
  - npm run coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
